/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DgIH9C3bVCn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Carousel } from "@/components/ui/carousel"
import './styles.css';
import QuestionCard from "./QuestionCard"
import { JSX, SVGProps, useState } from "react"
import { ProgramBenefits } from "./ProgramBenefits"
import { Plan } from "./Plan"
import { Expertise } from "./Expertise";
import BookSessionN from "./BookSessionN";
import { QuestionCards } from "./question-cards";
import { Header } from "./Header";
import Bottom from "./Bottom";
import LandingPage from "./LandingPage";

export function Component() {
  const [isPopupOpen, setIsPopupOpen] = useState(false);

  const openPopup = () => setIsPopupOpen(true);
  const closePopup = () => setIsPopupOpen(false);


  return (
    <>
          <LandingPage />
    <div className="flex flex-col min-h-[100dvh]">

      <Header />
      <main className="flex-1">
        <section className="w-full pt-12 md:pt-24 lg:pt-32">
          <div className="container grid gap-6 px-4 md:px-6 lg:gap-12 w-full">
            {/* <div className="video-container">
            <video
              autoPlay
              loop
              muted
              className="video mx-auto aspect-video overflow-hidden rounded-xl object-cover sm:w-full lg:order-last lg:aspect-square"
            >
              <source src="https://agrukf.webwave.dev/lib/agrukf/copy_DB8D6D2A-2D29-4680-B255-684DEC9C9BCB-1-lubaabhb.mp4" type="video/mp4" />
            </video>
          </div> */}
            <div className="flex flex-col space-y-4">
              <div className="">
                <h1 className="text-3xl font-bold tracking-tighter text-center sm:text-5xl xl:text-6xl">
                  Unleash Your Fitness Potential with FitFemme
                </h1>
              </div>
              <div className="w-full">
                <p className="max-w-[600px] mx-auto text-muted-foreground text-center md:text-xl">
                  Discover personalized training and nutrition plans tailored to help you achieve your fitness goals.
                </p>
              </div>

              <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 items-center mt-8 w-full">
                <div>
                  <QuestionCards />
                </div>
                <div className="image-container rounded-xl overflow-hidden">
                  <img
                    src="https://agrukf.webwave.dev/lib/agrukf/IMG_7533-lty93uvk.PNG"
                    alt="FitFemme Training"
                    className="image w-full h-auto object-contain"
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        <ProgramBenefits />
        <Plan />
        <Expertise />
        <section className="w-full py-12 md:py-24 lg:py-32 bg-muted px-24">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Get Started Today</h2>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Fill out the form below to book your first session with FitFemme.
              </p>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32 px-24">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">What Our Clients Say</h2>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Hear from real women who have transformed their lives with the help of FitFemme.
              </p>
            </div>
            <div className="divide-y rounded-lg border">
              <div className="grid w-full grid-cols-1 items-stretch justify-center divide-x md:grid-cols-2">
                <div className="mx-auto flex w-full flex-col items-start justify-center p-4 sm:p-8 space-y-4">
                  <div className="flex items-start gap-4">
                    <Avatar src={""} alt={""}>
                      <AvatarImage src="/placeholder-user.jpg" alt={""} />
                      <AvatarFallback src={""} alt={""}>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="text-sm font-medium leading-none">Jessica Doe</p>
                      <p className="text-sm text-muted-foreground">Lost 25 lbs in 3 months</p>
                    </div>
                  </div>
                  <p className="text-muted-foreground">
                    "Working with Sarah at FitFemme has been a game-changer\n for me. Her personalized approach and
                    unwavering support\n have helped me transform my body and my mindset."
                  </p>
                </div>
                <div className="mx-auto flex w-full flex-col items-start justify-center p-4 sm:p-8 space-y-4">
                  <div className="flex items-start gap-4">
                    <Avatar src={""} alt={""}>
                      <AvatarImage src="/placeholder-user.jpg" alt={""} />
                      <AvatarFallback src={""} alt={""}>LM</AvatarFallback>
                    </Avatar>
                    <div>
                      <p className="text-sm font-medium leading-none">Lisa Martinez</p>
                      <p className="text-sm text-muted-foreground">Gained 10 lbs of muscle</p>
                    </div>
                  </div>
                  <p className="text-muted-foreground">
                    "I was hesitant to try personal training, but FitFemme\n has exceeded all my expectations. The
                    results I've\n achieved have boosted my confidence and overall\n well-being."
                  </p>
                </div>
              </div>
            </div>
            <Carousel children={undefined} />
          </div>
        </section>
        <Bottom />
      </main>
    </div>
    </>
  )
}

function CheckIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function DumbbellIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M14.4 14.4 9.6 9.6" />
      <path d="M18.657 21.485a2 2 0 1 1-2.829-2.828l-1.767 1.768a2 2 0 1 1-2.829-2.829l6.364-6.364a2 2 0 1 1 2.829 2.829l-1.768 1.767a2 2 0 1 1 2.828 2.829z" />
      <path d="m21.5 21.5-1.4-1.4" />
      <path d="M3.9 3.9 2.5 2.5" />
      <path d="M6.404 12.768a2 2 0 1 1-2.829-2.829l1.768-1.767a2 2 0 1 1-2.828-2.829l2.828-2.828a2 2 0 1 1 2.829 2.828l1.767-1.768a2 2 0 1 1 2.829 2.829z" />
    </svg>
  )
}


function NutIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 4V2" />
      <path d="M5 10v4a7.004 7.004 0 0 0 5.277 6.787c.412.104.802.292 1.102.592L12 22l.621-.621c.3-.3.69-.488 1.102-.592A7.003 7.003 0 0 0 19 14v-4" />
      <path d="M12 4C8 4 4.5 6 4 8c-.243.97-.919 1.952-2 3 1.31-.082 1.972-.29 3-1 .54.92.982 1.356 2 2 1.452-.647 1.954-1.098 2.5-2 .595.995 1.151 1.427 2.5 2 1.31-.621 1.862-1.058 2.5-2 .629.977 1.162 1.423 2.5 2 1.209-.548 1.68-.967 2-2 1.032.916 1.683 1.157 3 1-1.297-1.036-1.758-2.03-2-3-.5-2-4-4-8-4Z" />
    </svg>
  )
}
