/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DgIH9C3bVCn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import { CheckIcon, DumbbellIcon, NutIcon } from 'lucide-react';
import './styles.css';
import { JSX, SVGProps, useState } from "react"

export function Expertise() {
  
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 px-24">
    <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
      <div className="space-y-3">
        <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Expertise You Can Trust</h2>
        <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
          Our certified personal trainer, Sarah, has over 10 years of experience helping women achieve their
          fitness goals through personalized training and nutrition plans.
        </p>
      </div>
      <div className="mx-auto grid max-w-5xl items-center gap-6 py-12 lg:grid-cols-2 lg:gap-12">
        <video
          autoPlay
          loop
          muted
          className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
        >
          <source src="/trainer-video.mp4" type="video/mp4" />
        </video>
        <div className="flex flex-col justify-center space-y-4">
          <ul className="grid gap-6">
            <li>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Customized Plans</h3>
                <p className="text-muted-foreground">
                  Every client receives a personalized training and nutrition plan tailored to their unique goals
                  and needs.
                </p>
              </div>
            </li>
            <li>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Holistic Approach</h3>
                <p className="text-muted-foreground">
                  We focus on improving your overall health and well-being, not just your physical appearance.
                </p>
              </div>
            </li>
            <li>
              <div className="grid gap-1">
                <h3 className="text-xl font-bold">Accountability</h3>
                <p className="text-muted-foreground">
                  Regular check-ins and progress tracking ensure you stay motivated and on track to reach your
                  goals.
                </p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </section>
  )
}

