/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DgIH9C3bVCn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import { CheckIcon, DumbbellIcon, NutIcon } from 'lucide-react';
import './styles.css';
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function Plan() {
  
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 bg-muted px-24">
    <div className="container px-4 md:px-6">
      <div className="flex flex-col items-center justify-center space-y-4 text-center">
        <div className="space-y-2">
          <h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">Choose Your Plan</h2>
          <p className="max-w-[900px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
            Select the plan that best fits your fitness goals and budget.
          </p>
        </div>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <Card className="flex flex-col">
          <CardHeader>
            <CardTitle>Online Training Basic</CardTitle>
            <CardDescription>$99/month</CardDescription>
          </CardHeader>
          <CardContent className="flex-1 grid gap-4">
            <ul className="grid gap-2 text-muted-foreground">
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                2 sessions per week
              </li>
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                Personalized training plan
              </li>
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                Nutrition guidance
              </li>
            </ul>
          </CardContent>
          <CardFooter>
            <Button className="w-full">Sign Up</Button>
          </CardFooter>
        </Card>
        <Card className="flex flex-col">
          <CardHeader>
            <CardTitle>Online Training Premium</CardTitle>
            <CardDescription>$149/month</CardDescription>
          </CardHeader>
          <CardContent className="flex-1 grid gap-4">
            <ul className="grid gap-2 text-muted-foreground">
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                3 sessions per week
              </li>
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                Personalized training and nutrition plan
              </li>
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                Unlimited email support
              </li>
            </ul>
          </CardContent>
          <CardFooter>
            <Button className="w-full">Sign Up</Button>
          </CardFooter>
        </Card>
        <Card className="flex flex-col">
          <CardHeader>
            <CardTitle>Online Training Elite</CardTitle>
            <CardDescription>$199/month</CardDescription>
          </CardHeader>
          <CardContent className="flex-1 grid gap-4">
            <ul className="grid gap-2 text-muted-foreground">
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                4 sessions per week
              </li>
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                Personalized training, nutrition, and lifestyle plan
              </li>
              <li>
                <CheckIcon className="mr-2 inline-block h-4 w-4 text-primary" />
                Unlimited email and video call support
              </li>
            </ul>
          </CardContent>
          <CardFooter>
            <Button className="w-full">Sign Up</Button>
          </CardFooter>
        </Card>
      </div>
    </div>
  </section>
  )
}

