/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DgIH9C3bVCn
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
"use client"
import { CheckIcon, DumbbellIcon, NutIcon } from 'lucide-react';
import './styles.css';
import { JSX, SVGProps, useState } from "react"

export function ProgramBenefits() {
  
  return (
        <section className="w-full py-14 md:py-24 lg:py-32 px-24 md:px-1">
          <div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6 lg:gap-10">
            <div className="space-y-3">
              <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Benefits of our Program</h2>
              <p className="mx-auto max-w-[700px] text-muted-foreground md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed">
                Our comprehensive fitness program offers a range of benefits to help you achieve your goals.
              </p>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
              <div className="flex flex-col items-start space-y-2">
              <div className="flex justify-center items-center sm:justify-start">
  <DumbbellIcon className="w-8 h-8 text-primary" />
</div>

                <h3 className="text-xl font-bold">Personalized Training</h3>
                <p className="text-muted-foreground">
                  Tailored workout plans designed to meet your unique needs and fitness level.
                </p>
              </div>
              <div className="flex flex-col items-start space-y-2">
                <NutIcon className="w-8 h-8 text-primary" />
                <h3 className="text-xl font-bold">Nutritional Guidance</h3>
                <p className="text-muted-foreground">
                  Comprehensive nutrition plans to support your fitness goals and overall health.
                </p>
              </div>
              <div className="flex flex-col items-start space-y-2">
                <CheckIcon className="w-8 h-8 text-primary" />
                <h3 className="text-xl font-bold">Accountability</h3>
                <p className="text-muted-foreground">
                  Regular check-ins and progress tracking to keep you motivated and on track.
                </p>
              </div>
            </div>
          </div>
        </section>
  )
}

